version: '3.8'

services:
  n8n:
    image: n8n:latest
    container_name: vod-search-engine-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=n8n.sqlite
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-changeme123}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows
    networks:
      - vod-search-network

volumes:
  n8n_data:
    driver: local

networks:
  vod-search-network:
    driver: bridge
